### ISSUE TITLE
Crem installation

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4q1a#8]
Hi @DhanshreeA 

I wanted to ask why did you choose to install CREM from its original repository instead of adding it to our repo ('pip install crem@git+https://github.com/DrrDom/crem.git@6ddfba45ab904f1a4b53610b7d38dd96fd82a1e5') - it's good that you fixed the version to a specific commit but still dangerous to rely on other's githubs to get the models.

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron, thanks for this question. I gave it some more thought. I do not have a strong reason for not copying the crem package to the model repo. I simply replicated the steps I used to install CREM on my machine in the Dockerfile. 
The only downside I see to installing CREM from the original repo is that if the author may just delete the repo / commit history in the future and so the install won't work. In this case we can create our fork from ersilia organization and use that for installing? Or would you rather I just copy the package? I'm good with either!

**Comment by miquelduranfrigola** [comment]
Hi, I would recommend against forking (we already have way too many repos).
Installing from git or directly copying the scripts inside `framework` are equally fine with me. @GemmaTuron feel free to decide

**Comment by DhanshreeA** [comment]
Hi @GemmaTuron should we close this issue?
